### ISSUE TITLE
Fitbit authentication is not working

### ISSUE THREAD

**Issue by manulita** [sealuzh/PersonalAnalytics#165]
The authentication window (only the one with the permissions, not the one with the email / password field) is showing up frequently. In the settings window, the button to revoke the Fitbit access token is not enabled, which indicates that it doesn't exist.

**Comment by s-mueller** [comment]
I'm not sure if this is really a bug. If there aren't any tokens to revoke, then the button is disabled. As soon as there are tokens there, the button is enabled. I can't reproduce that on my machine. 

Considering the authentication window: we have to check if this is fixed with the bugfix I just made or whether this is a different problem.

**Comment by s-mueller** [comment]
The first part of the bug should be fixed though.

**Comment by s-mueller** [comment]
@manulita Can you test whether this bug still happens? On my machine I couldn't reproduce it anymore.

**Comment by manulita** [comment]
Hey  @s-mueller , yes it is fixed. :) Thanks!

The part with the button to revoke the token was not meant to be a bug report, just additional information that this indicated that there actually is no token and the authentication really did not work. We can close this issue. It works on my machine and also on the machines of the participants.
